
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinalProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TableWishLists1081753
    {
        [DisplayName("清單編號")]
        public int Wish_Id { get; set; }
        [DisplayName("場域中文名稱")]
        public string CNName { get; set; }
        [DisplayName("場域英文名稱")]
        public string ENName { get; set; }
        [DisplayName("場域地址")]
        public string Address { get; set; }
        [DisplayName("帳號")]
        public string User_Account { get; set; }
        [DisplayName("場域代號")]
        public string Code { get; set; }
    }
}